### PR TITLE
minor bug fixes in documentation

### PR DESCRIPTION
**Pull request by kkvinjam**

### CODE REVIEW

**Review by CarmenAPuccio — APPROVED** [review]
LGTM

**Comment by CarmenAPuccio** [comment]
LGTM

**Review by CarmenAPuccio — APPROVED** [review]
LGTM

**Review by gcasilva — APPROVED** [review]

**Review by CarmenAPuccio — APPROVED** [review]
LGTM - 2nd review

**Review by CarmenAPuccio — APPROVED** [review]
LGTM - 3rd time

**Pull request merged**
